### ISSUE TITLE
Account Profile under windows buttons

### ISSUE THREAD

**Issue by v6r** [CharlieS1103/Glaze-theme#1]
![image](https://user-images.githubusercontent.com/83277314/163736018-1c574536-2b8f-4e44-90a9-3cdf535974c9.png)
![image](https://user-images.githubusercontent.com/83277314/163736019-9d17841f-c950-4cae-9932-19d1d462ecf4.png)

**Comment by v6r** [comment]
And if i scroll down in a playlist or in home etc. this pop up

![image](https://user-images.githubusercontent.com/83277314/163736166-c55bccd1-9360-4a39-9287-129bd864d7db.png)

**Comment by CharlieS1103** [comment]
I use a mac, if you want this issue fixed you'll unfortunately need to find someone who uses windoes

**Comment by v6r** [comment]
If anynone have also the Problem with the pfp button just use this code in your custom css

```
/* Push Spotify Profile downwards and make it look better*/
.main-userWidget-box {
  top: 30px;
  left: 1450px;
  background-color: #080808;
}
```

**Comment by v6r** [comment]
> And if i scroll down in a playlist or in home etc. this pop up
> 
> ![image](https://user-images.githubusercontent.com/83277314/163736166-c55bccd1-9360-4a39-9287-129bd864d7db.png)

this problem still didnt solved
